### ISSUE TITLE
composer包不能直接使用

### ISSUE THREAD

**Issue by ncusoho** [curder/aliyun-sms#1]

**Comment by curder** [comment]
你好，代码是我拷贝阿里云短信服务PHP的SDK，只是简单的加入了命名空间，调用方法可以查看`examples/Sms.php`中的实例代码，跟官方给出的demo一样。请问具体是报什么错呢？另外，如果你使用Laravel框架的话，也可以看看 [curder/laravel-aliyun-sms](https://github.com/curder/laravel-aliyun-sms)。
